var assert = require('chai').assert;
var linearSearch = require('../../search/linear-search');

describe('linear-search', function () {
    it('iterative', function () {
        assert.equal(linearSearch.iterative(3, []), -1);
        assert.equal(linearSearch.iterative(3, [1]), -1);
        assert.equal(linearSearch.iterative(1, [1]), 0);
        assert.equal(linearSearch.iterative(1, [1, 3, 5]), 0);
        assert.equal(linearSearch.iterative(3, [1, 3, 5]), 1);
        assert.equal(linearSearch.iterative(5, [1, 3, 5]), 2);
        assert.equal(linearSearch.iterative(0, [1, 3, 5]), -1);
        assert.equal(linearSearch.iterative(2, [1, 3, 5]), -1);
        assert.equal(linearSearch.iterative(4, [1, 3, 5]), -1);
        assert.equal(linearSearch.iterative(6, [1, 3, 5]), -1);
        assert.equal(linearSearch.iterative(1, [1, 3, 5, 7]), 0);
        assert.equal(linearSearch.iterative(3, [1, 3, 5, 7]), 1);
        assert.equal(linearSearch.iterative(5, [1, 3, 5, 7]), 2);
        assert.equal(linearSearch.iterative(7, [1, 3, 5, 7]), 3);
        assert.equal(linearSearch.iterative(0, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.iterative(2, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.iterative(4, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.iterative(6, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.iterative(8, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.iterative('efg', ['abc', 'bcd', 'cde', 'def', 'efg', 'fgh']), 4);
    });
    it('recursive', function () {
        assert.equal(linearSearch.recursive(3, []), -1);
        assert.equal(linearSearch.recursive(3, [1]), -1);
        assert.equal(linearSearch.recursive(1, [1]), 0);
        assert.equal(linearSearch.recursive(1, [1, 3, 5]), 0);
        assert.equal(linearSearch.recursive(3, [1, 3, 5]), 1);
        assert.equal(linearSearch.recursive(5, [1, 3, 5]), 2);
        assert.equal(linearSearch.recursive(0, [1, 3, 5]), -1);
        assert.equal(linearSearch.recursive(2, [1, 3, 5]), -1);
        assert.equal(linearSearch.recursive(4, [1, 3, 5]), -1);
        assert.equal(linearSearch.recursive(6, [1, 3, 5]), -1);
        assert.equal(linearSearch.recursive(1, [1, 3, 5, 7]), 0);
        assert.equal(linearSearch.recursive(3, [1, 3, 5, 7]), 1);
        assert.equal(linearSearch.recursive(5, [1, 3, 5, 7]), 2);
        assert.equal(linearSearch.recursive(7, [1, 3, 5, 7]), 3);
        assert.equal(linearSearch.recursive(0, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.recursive(2, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.recursive(4, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.recursive(6, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.recursive(8, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.recursive('efg', ['abc', 'bcd', 'cde', 'def', 'efg', 'fgh']), 4);
    });
    it('functional', function () {
        assert.equal(linearSearch.functional(3, []), -1);
        assert.equal(linearSearch.functional(3, [1]), -1);
        assert.equal(linearSearch.functional(1, [1]), 0);
        assert.equal(linearSearch.functional(1, [1, 3, 5]), 0);
        assert.equal(linearSearch.functional(3, [1, 3, 5]), 1);
        assert.equal(linearSearch.functional(5, [1, 3, 5]), 2);
        assert.equal(linearSearch.functional(0, [1, 3, 5]), -1);
        assert.equal(linearSearch.functional(2, [1, 3, 5]), -1);
        assert.equal(linearSearch.functional(4, [1, 3, 5]), -1);
        assert.equal(linearSearch.functional(6, [1, 3, 5]), -1);
        assert.equal(linearSearch.functional(1, [1, 3, 5, 7]), 0);
        assert.equal(linearSearch.functional(3, [1, 3, 5, 7]), 1);
        assert.equal(linearSearch.functional(5, [1, 3, 5, 7]), 2);
        assert.equal(linearSearch.functional(7, [1, 3, 5, 7]), 3);
        assert.equal(linearSearch.functional(0, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.functional(2, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.functional(4, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.functional(6, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.functional(8, [1, 3, 5, 7]), -1);
        assert.equal(linearSearch.functional('efg', ['abc', 'bcd', 'cde', 'def', 'efg', 'fgh']), 4);
    });
});
